name: Lint

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/lint.yml'
      - 'tardiff2/**'
      - 'tests/**'
      - '.pylintrc'
      - 'pyproject.toml'
      - 'ruff.toml'
      - 'tox.ini'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/lint.yml'
      - 'tardiff2/**'
      - 'tests/**'
      - '.pylintrc'
      - 'pyproject.toml'
      - 'ruff.toml'
      - 'tox.ini'
  workflow_dispatch:

jobs:
  lint:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
            - { toxenv:   ruff }
            - { toxenv: pylint }
            - { toxenv:   mypy }

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: "3"

    - name: Cache pip
      uses: actions/cache@v4
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: lint-pip-${{ matrix.toxenv }}

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
